mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/solcx/install.py", line 633, in _validate_installation
    installed_version = wrapper._get_solc_version(binary_path)
  File "/usr/local/lib/python3.8/dist-packages/solcx/wrapper.py", line 17, in _get_solc_version
    stdout_data = subprocess.check_output([str(solc_binary), "--version"], encoding="utf8")
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/.solcx/solc-v0.8.19', '--version']' died with <Signals.SIGBUS: 7>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/interfaces/cli.py", line 943, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/interfaces/cli.py", line 698, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/mythril/mythril_disassembler.py", line 172, in load_from_solidity
    solc_binary = self.solc_binary or util.extract_binary(file)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/ethereum/util.py", line 181, in extract_binary
    return solc_exists(version)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/ethereum/util.py", line 137, in solc_exists
    solcx.install_solc("v" + version)
  File "/usr/local/lib/python3.8/dist-packages/solcx/install.py", line 466, in install_solc
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/solcx/install.py", line 459, in install_solc
    _validate_installation(version, solcx_binary_path)
  File "/usr/local/lib/python3.8/dist-packages/solcx/install.py", line 636, in _validate_installation
    raise SolcInstallationError(
solcx.exceptions.SolcInstallationError: Downloaded binary would not execute, or returned unexpected output. If this issue persists, you can try to compile from source code using `solcx.compile_solc('0.8.19')`.

